# RCSnail properties
window_width: 960
window_height: 480
frame_width: 180
frame_height: 120
FPS: 30
track: eeden
# ZMQ properties
data_queue_port: 5551
controls_queue_port: 5552
# Procedural flags
model_override_enabled: true
expert_supervision_enabled: true
