# RCSnail properties
window_width: 960
window_height: 480
recording_width: 60
recording_height: 40
track: private
# ZMQ properties
data_queue_port: 5551
controls_queue_port: 5552
# Procedural flags
model_override_enabled: true
expert_supervision_enabled: true
